const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  //user
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  CREATE_CONTRACT_SUCCESS: "CREATE_CONTRACT_SUCCESS",
  CREATE_CONTRACT_FAIL: "CREATE_CONTRACT_FAIL",

  


});
export default actionTypes;