const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  //user
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  CREATE_CONTRACT_SUCCESS: "CREATE_CONTRACT_SUCCESS",
  CREATE_CONTRACT_FAIL: "CREATE_CONTRACT_FAIL",

  FETCH_ALL_CONTRACT_SUCCESS: "FETCH_ALL_CONTRACT_SUCCESS",
  FETCH_ALL_CONTRACT_FAIL: "FETCH_ALL_CONTRACT_FAIL",

  FETCH_LIST_CUSTOMER_SUCCESS: "FETCH_LIST_CUSTOMER_SUCCESS",
  FETCH_LIST_CUSTOMER_FAIL: "FETCH_LIST_CUSTOMER_FAIL",

  FETCH_CUSTOMER_PAGE_SUCCESS: "FETCH_CUSTOMER_PAGE_SUCCESS",
  FETCH_CUSTOMER_PAGE_FAIL: "FETCH_CUSTOMER_PAGE_FAIL",

  FETCH_LIST_USER_SUCCESS: "FETCH_LIST_USER_SUCCESS",
  FETCH_LIST_USER_FAIL: "FETCH_LIST_USER_FAIL",

  FETCH_PAYMENT_SUCCESS: "FETCH_PAYMENT_SUCCESS",
  FETCH_PAYMENT_FAIL: "FETCH_PAYMENT_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",


});
export default actionTypes;